### ISSUE TITLE
Support Mongo replica set

### ISSUE THREAD

**Issue by potomak** [potomak/tomatoes#141]
From Compose.io support:

> The benefits of a replica set don't come entirely without some work on the application and driver side. First you'll need to get the replica set URI from the Compose Admin section of your database. It will include your username and password as well as the hostnames of both hosts, their ports, and the database name and will look something like this:
>
> `mongodb://youruser:amazingpassword@candidate.18.mongolayer.com:10017,candidate.19.mongolayer.com:10017/yourdatabase`
>
> You'll also need to take into consideration things like [read preference](http://docs.mongodb.org/manual/core/read-preference/) and using some form of try / catch mechanism to handle errors including if your replica set has a stepdown event and switches primaries. Remember not to directly address one MongoDB server, but use the replica set URI which will discover all members. If you write to your primary directly, then when a stepdown happens in the case of a degraded host, instance, or networking issues you'll lose all the benefits of a highly available replica set.
>
> We wrote a short, introductory blog post about the topic here: https://blog.compose.io/support-desk-keeping-mongodb-live/

**Comment by dalpo** [comment]
The new replica sets configuration is online!

**Comment by potomak** [comment]
👍
