### ISSUE TITLE
Installation: 301 on cookbooks installation

### ISSUE THREAD

**Issue by Liarra** [potomak/tomatoes#143]
Hi! I am trying to set up a development server of my own. I am now on step 5 and I get a following error:

`[nina@leafblade tomatoes]$ librarian-chef install
Could not cache bluepill/1.0.6 <http://community.opscode.com/api/v1> from http://community.opscode.com/api/v1/cookbooks/bluepill because 301 Moved Permanently!
`
Can I do something to bypass this error?

**Comment by potomak** [comment]
@matteodepalo is the one who setup that process in the first place, let's see if he can help you solving this issue.

**Comment by matteodepalo** [comment]
@Liarra @potomak the Cheffile was updated 4 years ago so some of the libraries might have disappeared or they might have been moved to other places. To fix this we would need to look at the git urls in the Cheffile and update all of them to the latest versions. Also check if there are greater versions for `site 'http://community.opscode.com/api/v1'`. Try bumping that version to the latest one and see what happens.

**Comment by potomak** [comment]
@matteodepalo can you take a *quick look* at it and remove cheffile + doc if it's not usable anymore or update it please?

**Comment by matteodepalo** [comment]
@potomak it would take a while to update the Cheffile and the recipes to the latest version. I would personally remove the files as I don't have the time to update them unfortunately.

**Comment by potomak** [comment]
Ok, I'll add a task to remove them. Thanks.
