### ISSUE TITLE
Use a CSS framework

### ISSUE THREAD

**Issue by potomak** [potomak/tomatoes#147]
Tomatoes CSS is not based on any framework.

I'd like to use a small framework, with a limited amount of features, so no bootstrap/foundation.

I'd like to try http://getskeleton.com/, but I'm open to suggestions.

**Comment by dalpo** [comment]
@potomak What do you think about http://susy.oddbird.net/?

**Comment by potomak** [comment]
@dalpo I don't know susy.oddbird.net well enough to have any opinion on it.

**Comment by potomak** [comment]
Note: it seems that https://github.com/dhg/Skeleton is not maintained anymore, but https://github.com/skeleton-framework/skeleton-framework's fork seems to be.

**Comment by potomak** [comment]
Another alternative that I just found, that seems very similar to skeleton, is https://milligram.github.io/.

**Comment by yoX64** [comment]
I'd go with https://milligram.github.io/.

**Comment by potomak** [comment]
@yoX64 I'm working (slowly) in two different branches: in the first branch I tried Susy, in the second one I'm trying Bootstrap.

I must say that I liked the solution proposed by Susy at first, but I found soon too much friction to make it a viable option. When I started to build my own grid, that was the moment I realized Susy was not the best choice for me.

Before knowing that Milligram existed I started working on a branch to introduce Bootstrap. I must say that it seems the best option at the moment. The framework has tons of features and a very good documentation and Sass support.

Please note that most of my opinions are biased by the fact that I'm not a very good CSS developer, that's why I tend to choose ease of use and existing documentation/examples over a innovative solutions.

I will share some code as soon as possible.

**Comment by yoX64** [comment]
Bootstrap is a very good framework, but it really depends on what you need. It's important to choose a framework that will help you more than draws you back.

If you really need a big framework and you are going to use a lot of features that Bootstrap provides, then it's a great choice.

The reason why I opted for Milligram is that I thought that you need a minimal CSS framework, otherwise I would have chosen Bootstrap as well.

Let me know If I can help.

**Comment by potomak** [comment]
I ended up using Bootstrap.

I didn't do a very good job, there are many HTML elements that could be replaced by mixins included in the right classes.

Moreover a couple of elements, form errors and pagination controls, are still missing a restyling, but it's a starting point and, best of all, now Tomatoes supports small screens!
