### ISSUE TITLE
"Today" leaderboard improvements

### ISSUE THREAD

**Issue by dalpo** [potomak/tomatoes#179]
Run an async job to generate the "Today" leaderboard collection after a tomato create (with a debounce of 30 minutes).

**Comment by bugant** [comment]
@dalpo how do you handle the case in which for a whole day or more there is no new tomatoes? I mean when are you resetting the daily leaderboard? I cannot figure how to do this without a cron

**Comment by potomak** [comment]
Closed in favor of https://github.com/potomak/tomatoes/issues/206.
