### ISSUE TITLE
Project Chat room

### ISSUE THREAD

**Issue by pablosproject** [potomak/tomatoes#191]
Hi,
I propose to create a slack or gitter channel for start discussing about the project. I suggest those above IRC because they have better features, first of all the history, which is something that IRC is missing. # @

**Comment by dalpo** [comment]
I understand your request, but personally I don't like the idea of using a closed source chat to manage a FOSS project like tomatoes.

What do you think @bugant @potomak?

**Comment by potomak** [comment]
I agree with @dalpo. See also http://sircmpwn.github.io/2015/11/01/Please-stop-using-slack.html.

I registered a [#tomatoes](irc://irc.freenode.net/tomatoes) channel more than 2 years ago at http://freenode.net/ that could be used to chat about the project:

```
Information on #tomatoes:
Founder    : potomak
Successor  : freenode-staff
Registered : Jun 24 13:57:29 2014 (2y 16w 4d ago)
```

I will add info about the channel on the README soon.
