### ISSUE TITLE
GET API should not have JSON Body

### ISSUE THREAD

**Issue by pablosproject** [potomak/tomatoes#192]
I noticed that all the APIs have the access token passed as JSON parameter added to the body. This is ok for POST, but for GET requests, this is not correct.

[http://stackoverflow.com/questions/978061/http-get-with-request-body](http://stackoverflow.com/questions/978061/http-get-with-request-body)

Is it an issue to put the access token in the header of the request? What do you think @potomak?

**Comment by potomak** [comment]
You're right, I will fix the doc, thanks for the feedback!
