### ISSUE TITLE
Leaderboard not showing in web version

### ISSUE THREAD

**Issue by pablosproject** [potomak/tomatoes#196]
Leaderboard are not showing for my account on the web version. Don't know if this is related to the new API
![screen shot 2016-10-24 at 12 58 41](https://cloud.githubusercontent.com/assets/1416964/19643275/d2431672-99e9-11e6-9db5-d1538bf839b1.png)
 implementation.

**Comment by dalpo** [comment]
Related to: https://github.com/potomak/tomatoes/pull/193

**Comment by potomak** [comment]
Closed in favor of https://github.com/potomak/tomatoes/issues/206.
