### ISSUE TITLE
API data does not reflect web data

### ISSUE THREAD

**Issue by pablosproject** [potomak/tomatoes#197]
The JSON returned from the APIs foes not contain correct information. This is the JSON:

```
{
  "id": "580e6afc330dda074d17d768",
  "name": "Paolo Tagliani",
  "email": "pablosproject@gmail.com",
  "image": "https://avatars.githubusercontent.com/u/1416964?v=3",
  "time_zone": null,
  "color": "#000000",
  "volume": 2,
  "ticking": false,
  "work_hours_per_day": null,
  "average_hourly_rate": null,
  "currency": "USD",
  "currency_unit": "$",
  "tomatoes_counters": {
    "day": 0,
    "week": 0,
    "month": 0
  },
  "authorizations": [
    {
      "provider": "github",
      "uid": "1416964",
      "nickname": "pablosproject",
      "image": "https://avatars.githubusercontent.com/u/1416964?v=3"
    }
  ],
  "created_at": "2016-10-24T21:11:40.067+01:00",
  "updated_at": "2016-10-24T21:11:40.067+01:00"
}
```

Could be repeated with the following CURL: `curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 345032a3-f105-4c0c-5c4e-4013c5b3a7c9" "http://www.tomato.es/api/user?token=653bed8efab862310017359431fd11c9"`.

The tomatoes_counter, the average hourly rate, the color, timezone are not correct, see screenshot above.
Let me know if I can help more.
![screen shot 2016-10-24 at 22 14 36](https://cloud.githubusercontent.com/assets/1416964/19662375/715e6a98-9a37-11e6-9a14-3bb306c08bcf.png)
![screen shot 2016-10-24 at 22 14 49](https://cloud.githubusercontent.com/assets/1416964/19662381/76b9a124-9a37-11e6-97a8-6e98debbf240.png)

**Comment by potomak** [comment]
This issue is a side effect of https://github.com/potomak/tomatoes/issues/203, it has been solved by https://github.com/potomak/tomatoes/pull/204 and deployed with version [0.9.2](https://github.com/potomak/tomatoes/pull/205).
