### ISSUE TITLE
GIthub Token and API

### ISSUE THREAD

**Issue by pablosproject** [potomak/tomatoes#203]
I noticed that if we call the API authorization n times, each time the API return a different token. 

You can try by calling several times this: `curl -X POST -H "Content-Type: application/json" -H "Authorization: Basic cGFibG9zcHJvamVjdDpwYW9saXRvQGdpdGh1YkA4Nw==" -H "Cache-Control: no-cache" -H "Postman-Token: e8af5979-e1b9-ba9b-689c-8633cd8355e0" -d '{
	"client_id" : "bc037a4baea81c17986e",
	"client_secret" : "9232ddcd1ddf090a635d7b07679078ebed29fa82",
	"note" : "Tomatoes token"
}' "https://api.github.com/authorizations"`

If, after getting a github token I got a tomatoes Session token and call the API endpoint, I got a newly created user, with no data attached (hour rate, colors, counters, etc).

I think this is important because if a user uninstall the Tomatoes app, the re-install it, and login again using github he is not getting his old user, but a new one.

**Comment by bugant** [comment]
@pablosproject thank you for the report! You were indeed right. I've just merged a fix for it. As soon as it will be deployed you should be able to see if it is working as expected. If not, please re-open the issue.

@potomak can you please comment here when the latest version of the API is live?

**Comment by potomak** [comment]
The new API version is live as of yesterday, thanks to @dalpo, see https://github.com/potomak/tomatoes/pull/205.

**Comment by pablosproject** [comment]
Working! Good job.
