### ISSUE TITLE
Make a sound every now and then when user is inactive.

### ISSUE THREAD

**Issue by tellezhector** [potomak/tomatoes#93]
Sometimes someone could not hear the ringer after a pomodoro or a rest period has ended and then, keeps resting or keeps working.

An alert to make the user aware of the page asking for attention every 2 or 3 minutes would be useful for these cases.

There could be a limit of these alerts, for the case in which someone needs to leave the computer immediately. So the alerts doesn't keep ringing forever.

It seems easy (setTimeOut(blah blah)) and doesn't interfere with other features (and only plays on the client side).

**Comment by potomak** [comment]
Duplicate issue. @tellezhector please 👍 and follow https://github.com/potomak/tomatoes/issues/109 for updates.
